//package com.app.loan.entities;
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.Table;
//
//import lombok.AllArgsConstructor;
//import lombok.Getter;
//import lombok.NoArgsConstructor;
//import lombok.Setter;
//import lombok.ToString;
//
//
///**
// * Represents a payment made towards a loan.
// * Each payment is associated with a specific loan and contains details 
// * about the payment amount, EMI amount, and transaction status.
// */
//@Entity
//@Table(name ="loan_payment")
//@Getter
//@Setter
//@AllArgsConstructor
//@NoArgsConstructor
//@ToString(callSuper = true)
//public class LoanPayment extends BaseEntity{
//	
//	
//	/**
//     * Unique identifier for the loan payment.
//     * This is automatically generated by the database.
//     */
//	@Id
//	@GeneratedValue(strategy = GenerationType.IDENTITY)
//	private int payment_id;
//	
//	
//	/**
//     * The loan associated with this payment.
//     * Each payment is linked to a specific loan.
//     */
//	@ManyToOne(fetch = FetchType.EAGER)
//    @JoinColumn(name = "loan",nullable=false)
//	private Loan loanId;
//
//	
//	/**
//     * The total amount payable in this payment.
//     */
//	@Column(name = "payable_amount")
//	private float payableAmount;
//	
//	
//	/**
//     * The amount corresponding to the EMI (Equated Monthly Installment) in this payment.
//     */
//	@Column(name="emi_amount")
//	private float emiAmount;
//	
//	
//	/**
//     * The status of the transaction for this payment.
//     * This could include statuses like DEBITED, CREDITED.
//     */
//	@Column(name="transaction_status")
//	private TransactionStatus status;
//	
//
//}
